apiVersion: tf.kubeform.com/v1alpha1
kind: ModuleDefinition
metadata:
  creationTimestamp: null
  name: module-def-public
spec:
  moduleRef:
    git:
      ref: github.com/terraform-aws-modules/terraform-aws-s3-bucket
  provider:
    name: aws
    source: hashicorp/aws
  schema:
    properties:
      input:
        properties:
          acceleration_status:
            description: (Optional) Sets the accelerate configuration of an existing
              bucket. Can be Enabled or Suspended.
            type: string
          acl:
            description: (Optional) The canned ACL to apply. Defaults to 'private'.
              Conflicts with `grant`
            type: string
          attach_deny_insecure_transport_policy:
            description: Controls if S3 bucket should have deny non-SSL transport
              policy attached
            type: boolean
          attach_elb_log_delivery_policy:
            description: Controls if S3 bucket should have ELB log delivery policy
              attached
            type: boolean
          attach_lb_log_delivery_policy:
            description: Controls if S3 bucket should have ALB/NLB log delivery policy
              attached
            type: boolean
          attach_policy:
            description: Controls if S3 bucket should have bucket policy attached
              (set to `true` to use value of `policy` as bucket policy)
            type: boolean
          attach_public_policy:
            description: Controls if a user defined public bucket policy will be attached
              (set to `false` to allow upstream to apply defaults to the bucket)
            type: boolean
          attach_require_latest_tls_policy:
            description: Controls if S3 bucket should require the latest version of
              TLS
            type: boolean
          block_public_acls:
            description: Whether Amazon S3 should block public ACLs for this bucket.
            type: boolean
          block_public_policy:
            description: Whether Amazon S3 should block public bucket policies for
              this bucket.
            type: boolean
          bucket:
            description: (Optional, Forces new resource) The name of the bucket. If
              omitted, Terraform will assign a random, unique name.
            type: string
          bucket_prefix:
            description: (Optional, Forces new resource) Creates a unique bucket name
              beginning with the specified prefix. Conflicts with bucket.
            type: string
          control_object_ownership:
            description: Whether to manage S3 Bucket Ownership Controls on this bucket.
            type: boolean
          cors_rule:
            anyOf:
            - type: number
            - type: string
            - type: object
            description: List of maps containing rules for Cross-Origin Resource Sharing.
          create_bucket:
            description: Controls if S3 bucket should be created
            type: boolean
          force_destroy:
            description: (Optional, Default:false ) A boolean that indicates all objects
              should be deleted from the bucket so that the bucket can be destroyed
              without error. These objects are not recoverable.
            type: boolean
          grant:
            anyOf:
            - type: number
            - type: string
            - type: object
            description: An ACL policy grant. Conflicts with `acl`
          ignore_public_acls:
            description: Whether Amazon S3 should ignore public ACLs for this bucket.
            type: boolean
          lifecycle_rule:
            anyOf:
            - type: number
            - type: string
            - type: object
            description: List of maps containing configuration of object lifecycle
              management.
          logging:
            additionalProperties:
              type: string
            description: Map containing access bucket logging configuration.
            type: object
          object_lock_configuration:
            anyOf:
            - type: number
            - type: string
            - type: object
            description: Map containing S3 object locking configuration.
          object_ownership:
            description: 'Object ownership. Valid values: BucketOwnerEnforced, BucketOwnerPreferred
              or ObjectWriter. ''BucketOwnerEnforced'': ACLs are disabled, and the
              bucket owner automatically owns and has full control over every object
              in the bucket. ''BucketOwnerPreferred'': Objects uploaded to the bucket
              change ownership to the bucket owner if the objects are uploaded with
              the bucket-owner-full-control canned ACL. ''ObjectWriter'': The uploading
              account will own the object if the object is uploaded with the bucket-owner-full-control
              canned ACL.'
            type: string
          policy:
            description: (Optional) A valid bucket policy JSON document. Note that
              if the policy document is not specific enough (but still valid), Terraform
              may view the policy as constantly changing in a terraform plan. In this
              case, please make sure you use the verbose/specific version of the policy.
              For more information about building AWS IAM policy documents with Terraform,
              see the AWS IAM Policy Document Guide.
            type: string
          replication_configuration:
            anyOf:
            - type: number
            - type: string
            - type: object
            description: Map containing cross-region replication configuration.
          request_payer:
            description: (Optional) Specifies who should bear the cost of Amazon S3
              data transfer. Can be either BucketOwner or Requester. By default, the
              owner of the S3 bucket would incur the costs of any data transfer. See
              Requester Pays Buckets developer guide for more information.
            type: string
          restrict_public_buckets:
            description: Whether Amazon S3 should restrict public bucket policies
              for this bucket.
            type: boolean
          server_side_encryption_configuration:
            anyOf:
            - type: number
            - type: string
            - type: object
            description: Map containing server-side encryption configuration.
          tags:
            additionalProperties:
              type: string
            description: (Optional) A mapping of tags to assign to the bucket.
            type: object
          versioning:
            additionalProperties:
              type: string
            description: Map containing versioning configuration.
            type: object
          website:
            additionalProperties:
              type: string
            description: Map containing static web-site hosting or redirect configuration.
            type: object
        type: object
      output:
        properties:
          s3_bucket_arn:
            anyOf:
            - type: number
            - type: string
            - type: boolean
            - type: object
            description: The ARN of the bucket. Will be of format arn:aws:s3:::bucketname.
          s3_bucket_bucket_domain_name:
            anyOf:
            - type: number
            - type: string
            - type: boolean
            - type: object
            description: The bucket domain name. Will be of format bucketname.s3.amazonaws.com.
          s3_bucket_bucket_regional_domain_name:
            anyOf:
            - type: number
            - type: string
            - type: boolean
            - type: object
            description: 'The bucket region-specific domain name. The bucket domain
              name including the region name, please refer here for format. Note:
              The AWS CloudFront allows specifying S3 region-specific endpoint when
              creating S3 origin, it will prevent redirect issues from CloudFront
              to S3 Origin URL.'
          s3_bucket_hosted_zone_id:
            anyOf:
            - type: number
            - type: string
            - type: boolean
            - type: object
            description: The Route 53 Hosted Zone ID for this bucket's region.
          s3_bucket_id:
            anyOf:
            - type: number
            - type: string
            - type: boolean
            - type: object
            description: The name of the bucket.
          s3_bucket_region:
            anyOf:
            - type: number
            - type: string
            - type: boolean
            - type: object
            description: The AWS region this bucket resides in.
          s3_bucket_website_domain:
            anyOf:
            - type: number
            - type: string
            - type: boolean
            - type: object
            description: 'The domain of the website endpoint, if the bucket is configured
              with a website. If not, this will be an empty string. This is used to
              create Route 53 alias records. '
          s3_bucket_website_endpoint:
            anyOf:
            - type: number
            - type: string
            - type: boolean
            - type: object
            description: The website endpoint, if the bucket is configured with a
              website. If not, this will be an empty string.
        type: object
    required:
    - input
    type: object
status: {}
